<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
    <xsl:template match="/">
        <html xmlns="http://www.w3.org/1999/xhtml">
            <head>
                <title>XML Sitemap</title>
                <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
                <style type="text/css">
                    body {
                    font-family: Helvetica, Arial, sans-serif;
                    font-size: .8em;
                    color: #545353;
                    }
                    a {
                    color: #000;
                    text-decoration: none;
                    }
                    a:visited {
                    color: #777;
                    }
                    a:hover {
                    text-decoration: underline;
                    }
                    .content {
                    margin: 0 auto;
                    max-width: 1000px;
                    }
                    .expl {
                    margin: 18px 3px;
                    line-height: 1.2em;
                    }
                    .expl a {
                    color: #28A0DC;
                    font-weight: 600;
                    }
                    .expl a:visited {
                    color: #0078be;
                    }
                    table {
                    border: none;
                    border-collapse: collapse;
                    }
                    thead th {
                    border-bottom: 1px solid #000;
                    text-align:left;
                    padding-right:30px;
                    }
                    tbody tr:hover{
                    background: #F0F0F0;
                    }
                    footer{
                    font-size: .8em;
                    text-align: center;
                    }
                </style>
            </head>
            <body>
                <div class="content">
                    <h1>XML Sitemap</h1>
                    <p class="expl">
                        Generated by <a href="https://github.com/byng-systems/pimcore-sitemap-plugin">Pimcore Sitemap
                        Plugin</a>, this is an XML Sitemap, meant for consumption by search engines.<br/>You can find
                        more information about XML sitemaps on <a href="http://sitemaps.org">sitemaps.org</a>.
                    </p>
                    <xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &lt; 1">
                        <p class="expl">
                            This XML Sitemap contains
                            <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs.
                        </p>
                        <table id="sitemap" cellpadding="3">
                            <thead>
                                <tr>
                                    <th width="80%">URL</th>
                                    <th width="5%">Images</th>
                                    <th title="Last Modification" width="15%">Last Mod.</th>
                                </tr>
                            </thead>
                            <tbody>
                                <xsl:for-each select="sitemap:urlset/sitemap:url">
                                    <tr>
                                        <td>
                                            <xsl:variable name="itemURL">
                                                <xsl:value-of select="sitemap:loc"/>
                                            </xsl:variable>
                                            <a href="{$itemURL}">
                                                <xsl:value-of select="sitemap:loc"/>
                                            </a>
                                        </td>
                                        <td>
                                            <xsl:value-of select="count(image:image)"/>
                                        </td>
                                        <td>
                                            <xsl:value-of
                                                    select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)))"/>
                                        </td>
                                    </tr>
                                </xsl:for-each>
                            </tbody>
                        </table>
                    </xsl:if>
                </div>
                <footer>
                    <p>XSL inspired by <a href="https://yoast.com/wordpress/plugins/seo/">YoastSEO</a></p>
                </footer>
            </body>
        </html>
    </xsl:template>
</xsl:stylesheet>